### ISSUE TITLE
I tested it several times and it kept saying "Not found $$99999$$"

### ISSUE THREAD

**Issue by killnet1917** [pumpbin/pumpbin#2]
I tested it several times and it kept saying "Not found $$99999$$"
![Snipaste_2024-07-19_22-51-38](https://github.com/user-attachments/assets/7ff4cf08-a022-40bc-bffe-e01360f0bed4)

**Comment by b1nhack** [comment]
Your compiler may be optimizing away “$$99999$$”, you need to find a way to prevent the compiler from doing this optimization, different programming languages have different ways to do this, what language are you using?

**Comment by b1nhack** [comment]
This issue is inactive, please feel free to re-open the issue if the problem persists.
